// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhSpDtEzJ8cxrn0D6xUivl9V1tYKhbW-M',
    appId: '1:604600641466:web:0b736080bdc6fd3e125f83',
    messagingSenderId: '604600641466',
    projectId: 'm-app-754d5',
    authDomain: 'm-app-754d5.firebaseapp.com',
    storageBucket: 'm-app-754d5.firebasestorage.app',
    measurementId: 'G-XNR7FBF8WT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZg8whl1koksOjHQnQYA58Uri9w5hfM5A',
    appId: '1:604600641466:android:f0bd01ac5d52a071125f83',
    messagingSenderId: '604600641466',
    projectId: 'm-app-754d5',
    storageBucket: 'm-app-754d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmLUbEISMrd4Ictn9P_ZIS9POpdWHYJVs',
    appId: '1:604600641466:ios:bd3c3362b97d7023125f83',
    messagingSenderId: '604600641466',
    projectId: 'm-app-754d5',
    storageBucket: 'm-app-754d5.firebasestorage.app',
    iosBundleId: 'com.example.myweb',
  );
}
